nodeName: "lucene_server_primary"
hostName: "primary-node"
port: "8000"
replicationPort: "8001"
stateDir: "/user/app/primary_state"
indexDir: "/user/app/primary_index_base"
threadPoolConfiguration:
  maxSearchingThreads: 4
  maxIndexingThreads: 18
fileSendDelay: false
